name: stale_interview

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v5
      with:
        stale-issue-message: 'The issue of this Candidate has not been updated for too long.'
        days-before-stale: 1
