name: stale_interview

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        permissions:
          issues: write
        with:
          stale-issue-message: 'The issue of this Candidate hasn't been updated for too long.'
          days-before-stale: 1
